### ISSUE TITLE
Add timeout for requests

### ISSUE THREAD

**Issue by asottile** [asottile/PokemonGo-Map#34]
I saw the scraper get stuck trying to hit the api.  Here's the trace from when I killed it:

```
2016-07-28 13:21:28.117464 Traceback (most recent call last):
2016-07-28 13:21:28.117764   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
2016-07-28 13:21:28.118750     httplib_response = conn.getresponse(buffering=True)
2016-07-28 13:21:28.119150 TypeError: getresponse() got an unexpected keyword argument 'buffering'
2016-07-28 13:21:28.119613 
2016-07-28 13:21:28.119671 During handling of the above exception, another exception occurred:
2016-07-28 13:21:28.120094 
2016-07-28 13:21:28.120156 Traceback (most recent call last):
2016-07-28 13:21:28.120420   File "scrape.py", line 424, in <module>
2016-07-28 13:21:28.120725     exit(main())
2016-07-28 13:21:28.120874   File "scrape.py", line 389, in main
2016-07-28 13:21:28.121115     api_endpoint, access_token, profile_response, loc,
2016-07-28 13:21:28.121453   File "scrape.py", line 273, in get_heartbeat
2016-07-28 13:21:28.121772     loc=loc,
2016-07-28 13:21:28.121908   File "scrape.py", line 199, in get_profile
2016-07-28 13:21:28.122232     return retrying_api_req(api, access_token, req, loc=loc, useauth=useauth)
2016-07-28 13:21:28.122764   File "<decorator-gen-2>", line 2, in retrying_api_req
2016-07-28 13:21:28.123161   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/retry/api.py", line 74, in retry_decorator
2016-07-28 13:21:28.123910     logger)
2016-07-28 13:21:28.124029   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/retry/api.py", line 33, in __retry_internal
2016-07-28 13:21:28.124754     return f()
2016-07-28 13:21:28.124888   File "scrape.py", line 98, in retrying_api_req
2016-07-28 13:21:28.125197     response = api_req(*args, **kwargs)
2016-07-28 13:21:28.125473   File "scrape.py", line 130, in api_req
2016-07-28 13:21:28.125779     r = SESSION.post(api_endpoint, data=protobuf, verify=False)
2016-07-28 13:21:28.126212   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/requests/sessions.py", line 518, in post
2016-07-28 13:21:28.126995     return self.request('POST', url, data=data, json=json, **kwargs)
2016-07-28 13:21:28.127421   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
2016-07-28 13:21:28.128185     resp = self.send(prep, **send_kwargs)
2016-07-28 13:21:28.128481   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
2016-07-28 13:21:28.129232     r = adapter.send(request, **kwargs)
2016-07-28 13:21:28.129534   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
2016-07-28 13:21:28.130318     timeout=timeout
2016-07-28 13:21:28.130493   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
2016-07-28 13:21:28.131409     chunked=chunked)
2016-07-28 13:21:28.131593   File "/nail/home/asottile/trees/PokemonGo-Map/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
2016-07-28 13:21:28.132570     httplib_response = conn.getresponse()
2016-07-28 13:21:28.132880   File "/usr/lib64/python3.5/http/client.py", line 1174, in getresponse
2016-07-28 13:21:28.140092     response.begin()
2016-07-28 13:21:28.140316   File "/usr/lib64/python3.5/http/client.py", line 282, in begin
2016-07-28 13:21:28.140702     version, status, reason = self._read_status()
2016-07-28 13:21:28.141011   File "/usr/lib64/python3.5/http/client.py", line 243, in _read_status
2016-07-28 13:21:28.141446     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2016-07-28 13:21:28.141804   File "/usr/lib64/python3.5/socket.py", line 575, in readinto
2016-07-28 13:21:28.142937     return self._sock.recv_into(b)
2016-07-28 13:21:28.143178   File "/usr/lib64/python3.5/ssl.py", line 924, in recv_into
2016-07-28 13:21:28.143789     return self.read(nbytes, buffer)
2016-07-28 13:21:28.144018   File "/usr/lib64/python3.5/ssl.py", line 786, in read
2016-07-28 13:21:28.144329     return self._sslobj.read(len, buffer)
2016-07-28 13:21:28.144574   File "/usr/lib64/python3.5/ssl.py", line 570, in read
2016-07-28 13:21:28.144884     v = self._sslobj.read(len, buffer)
2016-07-28 13:21:28.145108 KeyboardInterrupt
```

**Comment by asottile** [comment]
I'm abandoning my efforts in this project
